spring:
  application:
    name:
      bebefriends
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    datasource:
      url: jdbc:h2:mem:test
    h2:
      console:
        enabled: true
        path: /h2-console
  security:
    user:
      name: user
      password: sample

springdoc:
  swagger-ui:
    path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG