@startuml
!pragma layout smetana
left to right direction

actor Parent

package auth {
  usecase (로그인) as authorize
  Parent --> auth
}

package user {
  usecase 회원가입 as join
  usecase (회원정보 변경) as modifyUser
  Parent --> user
}






package child {
  usecase (아이 추가) as postChild
  usecase (아이 목록 조회) as findChild
  Parent --> child
}









@enduml
